Movies Example Application
==========================

How to use Spring Boot, Spring Data Neo4j and Spring Data Rest together.

Spring Data Neo4j was the first Spring Data project, started by the CEOs Rod Johnson and Emil Eifrem.
It enables convenient integration of Neo4j in your Spring-based application.
It provides object-graph mapping functionality and other features common to the Spring Data projects.

[NOTE]
*This project uses Spring Data Neo4j 4 which is a complete rewrite from earlier versions.*
It is optimized for working with Neo4j Server and based on Neo4j's query language, Cypher.

The example project is described in detail on the http://neo4j.com/developer/example-project/[Neo4j Developer Site]

== Quickstart

. http://neo4j.com/download[Download, install and start Neo4j Server].
. open the web-interface at http://localhost:7474
. configure a username and password if you haven't already.
. run `:play movies` command, and click and run the Cypher statement to insert the dataset
. clone this project from GitHub
. update `src/main/resources/application.properties` with the username and password you set above.
. run the project with `mvn spring-boot:run`.

== Code Walkthrough

To use Neo4j with Spring Data Neo4j, you just add the dependency for http://projects.spring.io/spring-boot/[Spring-Boot] and http://projects.spring.io/spring-data-neo4j[Spring-Data-Neo4j] to your build setup.

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-neo4j</artifactId>
</dependency>

----
//include::pom.xml[tags=dependencies]

Annotate your `@NodeEntity` and `@RelationshipEntity`, you can use the OGM `Session` to access Neo4j APIs and object graph mapping functionality.

.Movie.java
[source,java]
----
@NodeEntity
public class Movie {

    @GraphId
    Long id;

    String title;

    int released;

    String tagline;

    @Relationship(type="ACTED_IN", direction = Relationship.INCOMING)
    List<Role> roles;
...
}
----
//include::src/main/java/movies/spring/data/neo4j/domain/Movie.java[tags=movie]


Additionally you can leverage the convenient Spring-Data repositories to get interface-based DAO implementations injected into your Spring Components.

.MovieRepository.java
[source,java]
----
@RepositoryRestResource(collectionResourceRel = "movies", path = "movies")
public interface MovieRepository extends PagingAndSortingRepository<Movie, Long> {

	Movie findByTitle(@Param("title") String title);

	@Query("MATCH (m:Movie) WHERE m.title =~ ('(?i).*'+{title}+'.*') RETURN m")
	Collection<Movie> findByTitleContaining(@Param("title") String title);

	@Query("MATCH (m:Movie)<-[r:ACTED_IN]-(a:Person) RETURN m,r,a LIMIT {limit}")
	Collection<Movie> graph(@Param("limit") int limit);
}
----
//include::src/main/java/movies/spring/data/neo4j/repositories/MovieRepository.java[tags=repository]

In our case we use the repository from a `MovieService` to compute the graph representation for the visualization.
The service is then injected into our main Boot application, which also doubles as `@RestMvcController` which exposes the `/graph` endpoint.

The other two endpoints for finding multiple movies by title and loading a single movie are provided out of the box by the http://projects.spring.io/spring-data-rest/[Spring-Data-Rest project] which exposes our `MovieRepository` as REST endpoints.

The rendering of the movie objects (and related entities) happens automatically out of the box via Jackson mapping.
To avoid circular JSON generation, the `JSOGGenerator` is used as id-generator.

== The Stack

These are the components of our Web Application:

* Application Type:         Spring-Boot Java Web Application (Jetty)
* Web framework:            Spring-Boot enabled Spring-WebMVC, Spring-Data-Rest
* Persistence Access:       Spring-Data-Neo4j 4.2.0
* Database:                 Neo4j-Server 3.0
* Frontend:                 jquery, bootstrap, http://d3js.org/[d3.js]

== Endpoints:

Get Movie

----
// JSON object for single movie with cast
curl http://localhost:8080/movies/search/findByTitle?title=The%20Matrix

// list of JSON objects for movie search results
curl http://localhost:8080/movies/search/findByTitleContaining?title=matrix

// JSON object for whole graph viz (nodes, links - arrays)
curl http://localhost:8080/graph
----
